name = "DataStructs"
uuid = "88ca5a4c-c0cb-4137-be7c-b24efc68920f"
authors = ["Jo√£o Vitor Hartung Toppa"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
